[package]
name = "rs-gen-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
rand = "0.9.2"
postcard = { version = "1.1.3", features = ["use-std"] }
num_cpus = "1.17.0"
